"""add job description fields to opportunities

Revision ID: d3ad46df3fdd
Revises: f8fb0b26c985
Create Date: 2026-09-25 16:12:39.091086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3ad46df3fdd'
down_revision: Union[str, Sequence[str], None] = 'f8fb0b26c985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('job_description', sa.Text(), nullable=True))
    op.add_column('opportunities', sa.Column('required_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('opportunities', sa.Column('preferred_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('opportunities', sa.Column('responsibilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('opportunities', sa.Column('qualifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('opportunities', sa.Column('experience_required', sa.String(length=150), nullable=True))
    op.add_column('opportunities', sa.Column('education_required', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opportunities', 'education_required')
    op.drop_column('opportunities', 'experience_required')
    op.drop_column('opportunities', 'qualifications')
    op.drop_column('opportunities', 'responsibilities')
    op.drop_column('opportunities', 'preferred_skills')
    op.drop_column('opportunities', 'required_skills')
    op.drop_column('opportunities', 'job_description')
    # ### end Alembic commands ###
