"""restore rich resume analysis schema

Revision ID: f8fb0b26c985
Revises: 44b3b47b93a2
Create Date: 2026-08-05 11:10:50.711992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8fb0b26c985'
down_revision: Union[str, Sequence[str], None] = '44b3b47b93a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume_analyses', sa.Column('name', sa.String(), nullable=True))
    op.add_column('resume_analyses', sa.Column('email', sa.String(), nullable=True))
    op.add_column('resume_analyses', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('resume_analyses', sa.Column('education',sa.JSON(),server_default=sa.text("'[]'::json"),nullable=False,))
    op.add_column('resume_analyses', sa.Column('experience', sa.JSON(), server_default=sa.text("'[]'::json"), nullable=False))
    op.add_column('resume_analyses', sa.Column('projects', sa.JSON(), server_default=sa.text("'[]'::json"), nullable=False))
    op.add_column('resume_analyses', sa.Column('ats_score', sa.Float(), server_default=sa.text("0"), nullable=False))
    op.add_column('resume_analyses', sa.Column('best_role', sa.String(), nullable=True))
    op.add_column('resume_analyses', sa.Column('missing_skills', sa.JSON(), server_default=sa.text("'[]'::json"), nullable=False))
    op.drop_column('resume_analyses', 'weaknesses')
    op.drop_column('resume_analyses', 'experience_years')
    op.drop_column('resume_analyses', 'analysis_score')
    op.drop_column('resume_analyses', 'summary')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume_analyses', sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('resume_analyses', sa.Column('analysis_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('resume_analyses', sa.Column('experience_years', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('resume_analyses', sa.Column('weaknesses', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('resume_analyses', 'missing_skills')
    op.drop_column('resume_analyses', 'best_role')
    op.drop_column('resume_analyses', 'ats_score')
    op.drop_column('resume_analyses', 'projects')
    op.drop_column('resume_analyses', 'experience')
    op.drop_column('resume_analyses', 'education')
    op.drop_column('resume_analyses', 'phone')
    op.drop_column('resume_analyses', 'email')
    op.drop_column('resume_analyses', 'name')
    # ### end Alembic commands ###
